version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: teamadb
      POSTGRES_USER: teama
      POSTGRES_PASSWORD: teama

  backend:
    build: ./back
    volumes:
      - ./back:/app
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    environment:
      - WATCHPACK_POLLING=true # ポーリングを有効にする
    depends_on:
      - backend

volumes:
  postgres_data:
